// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
//J-
package de.esoco.gwt.client.res;
import com.google.gwt.resources.client.CssResource;
public interface EsocoGwtCss extends CssResource {
  
  String error();
  
  String horizontal();

  String readonly();
  
  String vertical();

  @ClassName("gf-DataElement")
  String gfDataElement();
  
  @ClassName("gf-DataElementHeader")
  String gfDataElementHeader();
  
  @ClassName("gf-DataElementLabel")
  String gfDataElementLabel();
  
  @ClassName("gf-DataElementListDialog")
  String gfDataElementListDialog();
  
  @ClassName("gf-DataElementPanel")
  String gfDataElementPanel();
  
  @ClassName("gf-ButtonPanel")
  String gfButtonPanel();
  
  @ClassName("gf-DataElementDockPanel")
  String gfDataElementDockPanel();
  
  @ClassName("gf-DataElementGridPanel")
  String gfDataElementGridPanel();
  
  @ClassName("gf-DataElementFillPanel")
  String gfDataElementFillPanel();
  
  @ClassName("gf-DataElementFlowPanel")
  String gfDataElementFlowPanel();
  
  @ClassName("gf-DataElementFormPanel")
  String gfDataElementFormPanel();
  
  @ClassName("gf-DataElementGroupPanel")
  String gfDataElementGroupPanel();

  @ClassName("gf-DataElementSplitPanel")
  String gfDataElementSplitPanel();
  
  @ClassName("gf-DataElementStackPanel")
  String gfDataElementStackPanel();
  
  @ClassName("gf-DataElementTabsPanel")
  String gfDataElementTabsPanel();

  @ClassName("gf-DataElementDeckPanel")
  String gfDataElementDeckPanel();
  
  @ClassName("gf-EmptyCell")
  String gfEmptyCell();
  
  @ClassName("gf-LoginPanel")
  String gfLoginPanel();
  
  @ClassName("gf-PeriodCount")
  String gfPeriodCount();
  
  @ClassName("gf-PeriodUnit")
  String gfPeriodUnit();
  
  @ClassName("gf-SingleDataElement")
  String gfSingleDataElement();
  
  @ClassName("gf-Toolbar")
  String gfToolbar();
  
  @ClassName("gf-ToolbarBack")
  String gfToolbarBack();
  
  @ClassName("gf-ToolButton")
  String gfToolButton();
  
  @ClassName("gf-ToolSeparator")
  String gfToolSeparator();
  
  @ClassName("ga-ErrorMessage")
  String gaErrorMessage();
  
  @ClassName("ga-ProcessButtonPanel")
  String gaProcessButtonPanel();
  
  @ClassName("ga-ProcessPanel")
  String gaProcessPanel();
  
  @ClassName("ga-ProcessParamPanel")
  String gaProcessParamPanel();
  
  @ClassName("ga-ProcessSummaryPanel")
  String gaProcessSummaryPanel();
  
  @ClassName("ga-ProcessTitle")
  String gaProcessTitle();
  
  @ClassName("ga-ProcessTopPanel")
  String gaProcessTopPanel();}

