// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
//J-
package de.esoco.gwt.client.res;
import com.google.gwt.resources.client.CssResource;
public interface GwtApplicationCss extends CssResource {
    
  @ClassName("ga-ErrorMessage")
  String gaErrorMessage();
  
  @ClassName("ga-ProcessButtonPanel")
  String gaProcessButtonPanel();
  
  @ClassName("ga-ProcessPanel")
  String gaProcessPanel();
  
  @ClassName("ga-ProcessParamPanel")
  String gaProcessParamPanel();
  
  @ClassName("ga-ProcessSummaryPanel")
  String gaProcessSummaryPanel();
  
  @ClassName("ga-ProcessTitle")
  String gaProcessTitle();
  
  @ClassName("ga-ProcessTopPanel")
  String gaProcessTopPanel();
   
}

