// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
//J-
package de.esoco.gwt.client.res;
import com.google.gwt.resources.client.CssResource;
public interface GwtFrameworkCss extends CssResource {
  
  @ClassName("DialogAction")
  String dialogAction();
  
  @ClassName("EditTextAction")
  String editTextAction();
  
  @ClassName("EditTextValue")
  String editTextValue();
  
  String error();
  
  @ClassName("gf-ButtonPanel1")
  String gfButtonPanel1();
  
  @ClassName("gf-ButtonPanel2")
  String gfButtonPanel2();
  
  @ClassName("gf-ButtonPanel3")
  String gfButtonPanel3();
  
  @ClassName("gf-ButtonPanel4")
  String gfButtonPanel4();
  
  @ClassName("gf-DataElement")
  String gfDataElement();
  
  @ClassName("gf-DataElementHeader")
  String gfDataElementHeader();
  
  @ClassName("gf-DataElementLabel")
  String gfDataElementLabel();
  
  @ClassName("gf-DataElementListDialog")
  String gfDataElementListDialog();
  
  @ClassName("gf-DataElementListPanel")
  String gfDataElementListPanel();
  
  @ClassName("gf-DataElementPanel")
  String gfDataElementPanel();
  
  @ClassName("gf-DataElementFlowPanel")
  String gfDataElementFlowPanel();
  
  @ClassName("gf-DataElementFormPanel")
  String gfDataElementFormPanel();
  
  @ClassName("gf-DataElementFillPanel")
  String gfDataElementFillPanel();
  
  @ClassName("gf-DataElementSplitPanel")
  String gfDataElementSplitPanel();
  
  @ClassName("gf-DataElementStackPanel")
  String gfDataElementStackPanel();
  
  @ClassName("gf-DataElementTabPanel")
  String gfDataElementTabPanel();

  @ClassName("gf-EmptyCell")
  String gfEmptyCell();
  
  @ClassName("gf-LoginPanel")
  String gfLoginPanel();
  
  @ClassName("gf-MailMessagePanel")
  String gfMailMessagePanel();
  
  @ClassName("gf-PeriodCount")
  String gfPeriodCount();
  
  @ClassName("gf-PeriodUnit")
  String gfPeriodUnit();
  
  @ClassName("gf-SingleDataElement")
  String gfSingleDataElement();
  
  @ClassName("gf-Toolbar")
  String gfToolbar();
  
  @ClassName("gf-ToolbarBack")
  String gfToolbarBack();
  
  @ClassName("gf-ToolButton")
  String gfToolButton();
  
  @ClassName("gf-ToolSeparator")
  String gfToolSeparator();
  
  @ClassName("gwt-DialogBox")
  String gwtDialogBox();
  
  @ClassName("gwt-PushButton")
  String gwtPushButton();
  
  @ClassName("gwt-TextArea")
  String gwtTextArea();
  
  @ClassName("gwt-TextArea-readonly")
  String gwtTextAreaReadonly();
  
  String horizontal();
  
  @ClassName("MessageBox")
  String messageBox();
  
  @ClassName("MessageBoxContent")
  String messageBoxContent();
  
  @ClassName("MessageBoxIcon")
  String messageBoxIcon();
  
  @ClassName("MessageBoxText")
  String messageBoxText();
  
  @ClassName("ProcessStepFragment")
  String processStepFragment();
  
  String readonly();
  
  String vertical();
}

